POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json; charset=utf-8

{
    "date": "2015-01-25",
    "type": "Hospital",
    "specialist": "puoskari",
    "diagnosisCodes": [""],
    "description": "testing testing",
    "discharge": {
        "date": "2015-01-25",
        "criteria": "testings testings."
    }
}